curl -O "http://ajax.googleapis.com/ajax/libs/angular_material/0.11.4/angular-material.min.css"
curl -O "http://npmcdn.com/api-check@latest/dist/api-check.js"
curl -O "http://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js"
curl -O "http://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-animate.js"
curl -O "http://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-aria.js"
curl -O "http://ajax.googleapis.com/ajax/libs/angular_material/0.11.4/angular-material.min.js"
curl -O "http://npmcdn.com/angular-formly@latest/dist/formly.js"